#!/usr/bin/env python
"""
Fix migration table ordering to handle dependencies
"""
import re
import sys
from pathlib import Path

# Base tables that should be created first (no foreign key dependencies)
PRIORITY_TABLES = [
    'users',
    'tools',
    'workspaces',
]

def fix_migration_order(migration_file):
    """Reorder tables in migration file to handle dependencies"""
    with open(migration_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find all create_table operations
    pattern = r"(    op\.create_table\(['\"](\w+)['\"],.*?(?=\n    op\.|def downgrade))"
    matches = list(re.finditer(pattern, content, re.DOTALL))

    if not matches:
        print("No tables found in migration")
        return

    # Separate tables into priority and others
    priority_ops = []
    other_ops = []

    for match in matches:
        table_op = match.group(1)
        table_name = match.group(2)

        if table_name in PRIORITY_TABLES:
            priority_ops.append((table_name, table_op))
        else:
            other_ops.append((table_name, table_op))

    # Sort priority tables in the specified order
    priority_ops_sorted = []
    for table_name in PRIORITY_TABLES:
        for name, op in priority_ops:
            if name == table_name:
                priority_ops_sorted.append(op)
                break

    # Extract other operations
    other_ops_text = [op for _, op in other_ops]

    # Find the upgrade function
    upgrade_pattern = r"(def upgrade\(\) -> None:.*?\n)(.*?)(def downgrade)"

    def replacement(m):
        header = m.group(1)
        footer = m.group(3)

        # Combine operations: priority first, then others
        all_ops = priority_ops_sorted + other_ops_text
        new_body = "    # ### commands auto generated by Alembic - please adjust! ###\n" + "\n".join(all_ops) + "\n    # ### end Alembic commands ###\n\n"

        return header + new_body + footer

    new_content = re.sub(upgrade_pattern, replacement, content, flags=re.DOTALL)

    # Write back
    with open(migration_file, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"Reordered {len(matches)} tables in migration")
    print(f"Priority tables moved to beginning: {', '.join(PRIORITY_TABLES)}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python fix_migration_order.py <migration_file>")
        sys.exit(1)

    migration_file = Path(sys.argv[1])
    if not migration_file.exists():
        print(f"Migration file not found: {migration_file}")
        sys.exit(1)

    fix_migration_order(migration_file)
