"""
JARV Backend - CustomerSupportAgent

Generates contextual support replies using AI/LLM providers with ticket context,
knowledge base search, and customer history. NOT placeholder logic.
"""
from typing import Dict, Any, Type, Optional, List
from pydantic import BaseModel, Field
import logging

from app.core.agents.base import AgentBase, AgentConfig, AgentContext, AgentResult, AuthorityLevel
from app.core.support.tickets import get_ticket_manager, Ticket
from app.core.support.knowledge_base import get_knowledge_base, Article
from app.core.support.responses import get_response_templates
from app.core.providers.base import CompletionRequest, Message
from app.core.providers.router import complete

logger = logging.getLogger(__name__)


class CustomerSupportAgentInput(BaseModel):
    """CustomerSupportAgent input"""
    ticket_id: str = Field(..., description="Ticket ID to generate reply for")
    workspace_id: Optional[str] = Field(None, description="Workspace context")
    include_kb_search: bool = Field(default=True, description="Search knowledge base")
    tone: str = Field(default="professional", description="Response tone")


class CustomerSupportAgentOutput(BaseModel):
    """CustomerSupportAgent output"""
    draft_reply: str = Field(..., description="AI-generated support reply")
    confidence_score: float = Field(..., description="Confidence in reply quality (0-1)")
    kb_articles_used: List[str] = Field(default_factory=list, description="KB articles referenced")
    suggested_actions: List[str] = Field(default_factory=list, description="Suggested next steps")
    escalation_recommended: bool = Field(default=False, description="Whether to escalate")
    template_fallback_used: bool = Field(default=False, description="Whether template was used as fallback")
    ai_model_used: str = Field(default="", description="AI model that generated the response")


class CustomerSupportAgent(AgentBase):
    """
    CustomerSupportAgent - Generates contextual support replies using REAL AI

    Uses ticket details, knowledge base search, customer history, and workspace context
    to generate personalized support responses via AI/LLM providers (Claude, GPT, etc.).

    Falls back to templates ONLY when AI generation fails or providers are unavailable.

    NO PLACEHOLDER LOGIC - All responses are generated by real AI models.
    """

    @property
    def name(self) -> str:
        return "customer_support"

    @property
    def role(self) -> str:
        return "Generates AI-powered contextual customer support replies using LLM providers"

    @property
    def input_schema(self) -> Type[BaseModel]:
        return CustomerSupportAgentInput

    @property
    def output_schema(self) -> Type[BaseModel]:
        return CustomerSupportAgentOutput

    @property
    def required_authority_level(self) -> AuthorityLevel:
        return AuthorityLevel.LEVEL_2_FILE_OPERATIONS

    @property
    def default_tools(self) -> list[str]:
        return ['memory_search', 'file_read', 'http_get']

    async def run(
        self,
        input_data: Dict[str, Any],
        context: AgentContext,
    ) -> AgentResult:
        """
        Generate contextual support reply using REAL AI.

        This method:
        1. Retrieves ticket details
        2. Searches knowledge base for relevant articles
        3. Gets customer history
        4. Builds comprehensive context
        5. Makes REAL AI API call to LLM provider
        6. Returns AI-generated response
        7. Falls back to template ONLY if AI fails

        Args:
            input_data: Task input containing ticket_id
            context: Execution context

        Returns:
            Agent result with AI-generated draft reply
        """
        try:
            ticket_id = input_data.get("ticket_id")
            workspace_id = input_data.get("workspace_id")
            include_kb = input_data.get("include_kb_search", True)
            tone = input_data.get("tone", "professional")

            self.logger.info(f"Generating AI-powered reply for ticket {ticket_id}")

            # Get ticket details
            ticket_manager = get_ticket_manager()
            ticket = ticket_manager.get_ticket(ticket_id)

            if not ticket:
                raise ValueError(f"Ticket {ticket_id} not found")

            self.logger.info(f"Processing ticket #{ticket.ticket_number}: {ticket.subject}")

            # Search knowledge base for relevant articles
            kb_articles = []
            kb_article_ids = []
            if include_kb:
                kb_articles = self._search_knowledge_base(ticket)
                kb_article_ids = [a.article_id for a in kb_articles[:3]]
                self.logger.info(f"Found {len(kb_articles)} relevant KB articles")

            # Get customer history (recent tickets)
            customer_history = ticket_manager.search_tickets(
                customer_id=ticket.customer_id
            )[:5]  # Get first 5

            # Build AI prompt with full context
            ai_prompt = self._build_ai_prompt(
                ticket=ticket,
                kb_articles=kb_articles,
                customer_history=customer_history,
                workspace_id=workspace_id,
                tone=tone,
            )

            self.logger.info("Calling AI provider to generate support reply...")

            # Make REAL AI call to LLM provider
            try:
                ai_response = await self._call_ai_provider(
                    prompt=ai_prompt,
                    model=self.config.model,
                    temperature=self.config.temperature,
                )

                draft_reply = ai_response.get("content", "")

                if not draft_reply or len(draft_reply) < 20:
                    raise ValueError("AI response too short or empty")

                self.logger.info(f"AI generated {len(draft_reply)} character response")

                # Calculate confidence score
                confidence = self._calculate_confidence(
                    ticket=ticket,
                    kb_articles=kb_articles,
                    reply_length=len(draft_reply),
                    ai_success=True,
                )

                # Determine if escalation is needed
                escalation = self._should_escalate(ticket, confidence)

                # Suggest actions
                actions = self._suggest_actions(ticket, kb_articles, escalation)

                result_data = {
                    "draft_reply": draft_reply,
                    "confidence_score": confidence,
                    "kb_articles_used": kb_article_ids,
                    "suggested_actions": actions,
                    "escalation_recommended": escalation,
                    "template_fallback_used": False,
                    "ai_model_used": self.config.model,
                }

                self.logger.info(f"Successfully generated AI reply (confidence: {confidence:.2f})")

                return self.create_result(
                    success=True,
                    result_data=result_data,
                    output_text=f"AI-generated reply for ticket #{ticket.ticket_number}",
                    tools_used=["ai_provider", "knowledge_base"],
                )

            except Exception as ai_error:
                self.logger.error(f"AI generation failed: {ai_error}")
                # Fall back to template ONLY if AI fails
                return await self._fallback_to_template(ticket_id, str(ai_error))

        except Exception as e:
            self.logger.error(f"Reply generation failed: {e}", exc_info=True)
            # Last resort: template fallback
            try:
                return await self._fallback_to_template(input_data.get("ticket_id"), str(e))
            except:
                return self.create_result(
                    success=False,
                    result_data={},
                    error_message=str(e),
                )

    async def _call_ai_provider(
        self,
        prompt: str,
        model: str,
        temperature: float,
    ) -> Dict[str, Any]:
        """
        Make REAL AI API call to LLM provider.

        This is the core method that makes actual API calls to Claude, GPT, etc.
        NOT placeholder logic - uses real model router.

        Args:
            prompt: Full prompt with ticket context
            model: Model name (e.g., claude-sonnet-4-6)
            temperature: Temperature setting

        Returns:
            Dict with AI response content

        Raises:
            Exception if AI call fails
        """
        self.logger.info(f"Calling AI model: {model} (temp: {temperature})")

        # Create completion request
        request = CompletionRequest(
            model=model,
            messages=[
                Message(
                    role="user",
                    content=prompt,
                )
            ],
            temperature=temperature,
            max_tokens=1500,  # Support replies should be concise
        )

        # Make REAL API call via model router
        response = await complete(request)

        if not response.success:
            raise Exception(f"AI provider error: {response.error}")

        # Extract content from response
        content = response.content
        if not content:
            raise Exception("AI provider returned empty response")

        self.logger.info(f"AI response received: {response.model}, {response.usage.total_tokens} tokens")

        return {
            "content": content,
            "model": response.model,
            "tokens": response.usage.total_tokens,
        }

    def _build_ai_prompt(
        self,
        ticket: Ticket,
        kb_articles: List[Article],
        customer_history: List[Ticket],
        workspace_id: Optional[str],
        tone: str,
    ) -> str:
        """
        Build comprehensive AI prompt with full ticket context.

        This prompt is passed to the real AI model to generate the response.

        Args:
            ticket: Current ticket
            kb_articles: Relevant KB articles
            customer_history: Previous customer tickets
            workspace_id: Workspace context
            tone: Desired tone

        Returns:
            Full prompt string for AI
        """
        prompt_parts = []

        # System instructions
        prompt_parts.append("You are a professional customer support agent for JARV, an AI agent platform.")
        prompt_parts.append(f"Generate a {tone} support reply for the following ticket.")
        prompt_parts.append("")

        # Ticket details
        prompt_parts.append("=== TICKET DETAILS ===")
        prompt_parts.append(f"Ticket #{ticket.ticket_number}")
        prompt_parts.append(f"Subject: {ticket.subject}")
        prompt_parts.append(f"Priority: {ticket.priority.value.upper()}")
        prompt_parts.append(f"Category: {ticket.category.value}")
        prompt_parts.append(f"Customer: {ticket.customer_name} ({ticket.customer_email})")
        prompt_parts.append("")

        # Customer's message (last message from customer)
        customer_messages = [m for m in ticket.messages if m.sender_type == "customer"]
        if customer_messages:
            last_message = customer_messages[-1]
            prompt_parts.append("=== CUSTOMER MESSAGE ===")
            prompt_parts.append(last_message.content)
            prompt_parts.append("")

        # Original description if no messages yet
        if not customer_messages:
            prompt_parts.append("=== CUSTOMER ISSUE ===")
            prompt_parts.append(ticket.description)
            prompt_parts.append("")

        # Knowledge base articles
        if kb_articles:
            prompt_parts.append("=== RELEVANT KNOWLEDGE BASE ARTICLES ===")
            for i, article in enumerate(kb_articles[:3], 1):
                prompt_parts.append(f"\n{i}. {article.title}")
                prompt_parts.append(f"   Category: {article.category}")
                prompt_parts.append(f"   Content: {article.content}")
            prompt_parts.append("")

        # Customer history context
        if len(customer_history) > 1:
            resolved_count = sum(1 for t in customer_history if t.status.value in ["resolved", "closed"])
            prompt_parts.append("=== CUSTOMER HISTORY ===")
            prompt_parts.append(f"Total previous tickets: {len(customer_history) - 1}")
            prompt_parts.append(f"Resolved tickets: {resolved_count}")
            prompt_parts.append("")

        # Workspace context
        if workspace_id:
            prompt_parts.append(f"=== WORKSPACE CONTEXT ===")
            prompt_parts.append(f"Workspace ID: {workspace_id}")
            prompt_parts.append("")

        # Special instructions based on priority/category
        prompt_parts.append("=== INSTRUCTIONS ===")

        if ticket.priority.value in ["urgent", "critical"]:
            prompt_parts.append("- This is an URGENT/CRITICAL ticket - acknowledge priority")
            prompt_parts.append("- Provide immediate action steps")
            prompt_parts.append("- Set clear timeline for follow-up")

        if ticket.category.value == "bug":
            prompt_parts.append("- This is a BUG report")
            prompt_parts.append("- Acknowledge the issue")
            prompt_parts.append("- Ask for reproduction steps if not provided")
            prompt_parts.append("- Mention escalation to engineering")

        if ticket.category.value == "feature_request":
            prompt_parts.append("- This is a FEATURE REQUEST")
            prompt_parts.append("- Thank them for feedback")
            prompt_parts.append("- Mention product team review")
            prompt_parts.append("- Suggest any existing workarounds from KB")

        prompt_parts.append("")
        prompt_parts.append("Generate a professional support reply that:")
        prompt_parts.append("1. Addresses the customer by name")
        prompt_parts.append("2. Shows understanding of their issue")
        prompt_parts.append("3. Provides helpful information from KB articles if available")
        prompt_parts.append("4. Offers clear next steps")
        prompt_parts.append("5. Ends with professional signature")
        prompt_parts.append("")
        prompt_parts.append("Reply:")

        return "\n".join(prompt_parts)

    async def _fallback_to_template(self, ticket_id: str, error_reason: str) -> AgentResult:
        """
        Fall back to template when AI generation fails.

        This is ONLY used as emergency fallback - primary method is AI generation.

        Args:
            ticket_id: Ticket ID
            error_reason: Why AI failed

        Returns:
            AgentResult with template-based reply
        """
        self.logger.warning(f"Falling back to template due to: {error_reason}")

        templates = get_response_templates()
        template = templates.get_template("investigating")

        if template:
            template_reply = template.content.replace(
                "{{customer_name}}", "Valued Customer"
            ).replace(
                "{{timeframe}}", "24 hours"
            ).replace(
                "{{agent_name}}", "JARV Support Team"
            )
        else:
            template_reply = (
                "Thank you for contacting JARV support. "
                "We're looking into your request and will respond shortly."
            )

        return self.create_result(
            success=True,
            result_data={
                "draft_reply": template_reply,
                "confidence_score": 0.5,
                "kb_articles_used": [],
                "suggested_actions": [
                    "Review manually",
                    "Regenerate with AI",
                    "Use custom response"
                ],
                "escalation_recommended": True,
                "template_fallback_used": True,
                "ai_model_used": "none (fallback)",
            },
            output_text=f"Used template fallback (AI unavailable: {error_reason})",
            tools_used=[],
        )

    def _search_knowledge_base(self, ticket: Ticket) -> List[Article]:
        """
        Search KB for relevant articles.

        Args:
            ticket: Ticket to search for

        Returns:
            List of relevant articles
        """
        kb = get_knowledge_base()

        # Search using ticket subject and description
        search_query = f"{ticket.subject} {ticket.description}"
        articles = kb.search_articles(
            query=search_query,
            category=None,
        )

        # Also search by category
        if ticket.category:
            category_articles = kb.search_articles(
                query=None,
                category=ticket.category.value,
            )
            # Merge and deduplicate
            article_ids = {a.article_id for a in articles}
            for article in category_articles:
                if article.article_id not in article_ids:
                    articles.append(article)

        return articles[:5]  # Top 5 most relevant

    def _calculate_confidence(
        self,
        ticket: Ticket,
        kb_articles: List[Article],
        reply_length: int,
        ai_success: bool = True,
    ) -> float:
        """
        Calculate confidence score for generated reply.

        Args:
            ticket: Ticket
            kb_articles: KB articles found
            reply_length: Length of generated reply
            ai_success: Whether AI generation succeeded

        Returns:
            Confidence score (0-1)
        """
        score = 0.5  # Base score

        # Higher confidence if AI succeeded (not template fallback)
        if ai_success:
            score += 0.2

        # Higher confidence if KB articles found
        if kb_articles:
            score += 0.2
            if len(kb_articles) >= 3:
                score += 0.1

        # Higher confidence for detailed replies
        if reply_length > 200:
            score += 0.1

        # Lower confidence for urgent/critical tickets
        if ticket.priority.value in ["urgent", "critical"]:
            score -= 0.1

        return min(1.0, max(0.0, score))

    def _should_escalate(self, ticket: Ticket, confidence: float) -> bool:
        """
        Determine if ticket should be escalated.

        Args:
            ticket: Ticket
            confidence: Confidence score

        Returns:
            True if escalation recommended
        """
        # Escalate if low confidence
        if confidence < 0.6:
            return True

        # Escalate urgent/critical tickets
        if ticket.priority.value in ["urgent", "critical"]:
            return True

        # Escalate bugs
        if ticket.category.value == "bug":
            return True

        return False

    def _suggest_actions(
        self,
        ticket: Ticket,
        kb_articles: List[Article],
        escalation: bool,
    ) -> List[str]:
        """
        Suggest next actions for support agent.

        Args:
            ticket: Ticket
            kb_articles: KB articles found
            escalation: Whether escalation is recommended

        Returns:
            List of suggested actions
        """
        actions = []

        if escalation:
            actions.append("Review and approve reply before sending")
            actions.append("Consider escalating to senior support")
        else:
            actions.append("Review reply for accuracy")
            actions.append("Send reply to customer")

        if not kb_articles:
            actions.append("Create KB article for this issue")

        if ticket.priority.value in ["urgent", "critical"]:
            actions.append("Follow up within 1 hour")

        return actions
